# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ae6fe64fd7fbafb2940798b4c009464761f820a3519eb2e1c3f83cb5e18bc0c1855041f9372181ba0b4344664be781a2ece3366528e414f34adc5bc0398baa8

test:
  secret_key_base: a747b8a49b7bcdb7435b686bae580e25264dc006a9532fb7f5cf5044b93f64d27c4487f3f95858795898cee3116a3d8033eabece88c2a683cbeef754513029de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
